# Generated by Django 2.1.2 on 2018-11-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.IntegerField()),
                ('name', models.CharField(max_length=15)),
                ('designation', models.CharField(choices=[('Fresher', 'Fresher'), ('SoftwareDeveloper', 'SD'), ('TechnicalAssocoiate', 'TA'), ('HumanResource', 'HR')], default='Fresher', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalBehaviour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provideo_id', models.IntegerField()),
                ('name', models.CharField(max_length=15)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityTraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.IntegerField()),
                ('name', models.CharField(max_length=15)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(max_length=250)),
            ],
        ),
    ]
