# Generated by Django 2.1.2 on 2018-11-28 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_securitytraining_thumb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='ProfessionalBehaviour',
        ),
        migrations.DeleteModel(
            name='SecurityTraining',
        ),
    ]
