# Generated by Django 2.1.2 on 2018-11-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_employee_professionalbehaviour_securitytraining'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securitytraining',
            name='message',
        ),
        migrations.AddField(
            model_name='professionalbehaviour',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
