# Generated by Django 2.1.5 on 2019-01-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_remove_event_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='expense_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
